import "./globals.css";
import { Inter } from "next/font/google";
import { ProviderWrapper } from "@/redux/provider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-w-[800px] px-10">
        <ProviderWrapper>
          <Navbar></Navbar>
          {children}
        </ProviderWrapper>
      </body>
    </html>
  );
}
